baseURL: "https://figan.id/"
title: figan.id
theme: PaperMod

# build
buildDrafts: false
buildFuture: false
buildExpired: false

enableGitInfo : true

copyright :  © 2023 Talenta Maulana Figan

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  keywords: [Portfolio]
  author: Me
  # author: ["Me", "You"] # multiple authors
  DateFormat: "May 15, 2023"
  defaultTheme: dark # dark, light
  disableThemeToggle: false

  profileMode:
        enabled: true
        title: Talenta Figan
        subtitle: "Freelance Software Engginer"
        imageUrl: "talentafigan.jpg" # optional
        imageTitle: "Talenta Figan" # optional
        imageWidth: 120 # custom size
        imageHeight: 120 # custom size
        buttons:
          - name: Let me work with you!
            url: ""
          - name: See Portofolio
            url: "https://github.com/talentafigan"

  socialIcons:
    - name: github
      url: "https://github.com/talentafigan"
    - name: linkedin
      url: "https://www.linkedin.com/in/talenta-figan-21364b180/"