baseURL: "https://talentafigan.github.io/"
title: Talenta Figan
theme: PaperMod

# build
buildDrafts: false
buildFuture: false
buildExpired: false

enableGitInfo : true

copyright :  © 2024 Talenta Figan

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  keywords: [Portfolio]
  author: Figan
  # author: ["Me", "You"] # multiple authors
  defaultTheme: light # dark, light
  disableThemeToggle: false

  profileMode:
        enabled: true
        title: Talenta Figan
        subtitle: "Software Engginer, Tech enthusiast"
        imageUrl: "talentafigan.jpg" # optional
        imageTitle: "Talenta Figan" # optional
        imageWidth: 120 # custom size
        imageHeight: 120 # custom size
        buttons:
          - name: Work with me  
            url: "/contact"
          - name: See my works
            url: "https://talentafigan.github.io/cv/#professional-projects"

  socialIcons:
    - name: github
      url: "https://github.com/talentafigan"
    - name: linkedin
      url: "https://www.linkedin.com/in/talenta-figan-21364b180/"


menu:
  main:
    - identifier: about
      name: About Me
      url: /cv/
      weight: 10
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 10